#ifndef ROBOX_CONTROLLER_CONFIG_H
#define ROBOX_CONTROLLER_CONFIG_H

#define BAUDRATE 9600
#define MESSAGE_START_CHAR '<'
#define MESSAGE_STOP_CHAR '>'
#define MESSAGE_SIZE 255

#endif// ROBOX_CONTROLLER_CONFIG_H