//
// Created by luke on 15-05-22.
//

#ifndef ROBOX_USER_INTERFACE_GLOBAL_CONFIG_H
#define ROBOX_USER_INTERFACE_GLOBAL_CONFIG_H

#define REQUEST_START_CHAR '<'
#define REQUEST_STOP_CHAR '>'

#define RESPONSE_START_CHAR '#'
#define RESPONSE_STOP_CHAR ';'

#define LOG_START_CHAR '@'
#define LOG_STOP_CHAR ';'
#define LOG_PART_SEPARATOR '|'

#define WRITE_DELAY_US 150

#endif//ROBOX_USER_INTERFACE_GLOBAL_CONFIG_H
